apiVersion: ENC[AES256_GCM,data:P2c=,iv:onWOkWIR8y7t/tX17EC50hOJmbYbPbr2YaSMUdbm2hU=,tag:v1e5yF9kQEen+89V9n1OAQ==,type:str]
kind: ENC[AES256_GCM,data:APKlnv9O,iv:lTJCn17cAtfmExWywh/0rw4TghHPXXOJt2o7yQM4qXM=,tag:fdavmt9YIM+gbgHy0qeqiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MapN54b9PJ1vl1JkzkafeqoAjkg=,iv:zth93wgpLwBq8SdskPdhGGl+nV6AshGuI9kRBXte9GA=,tag:e1KM9HOeNXqxhGuSOpyRyQ==,type:str]
    namespace: ENC[AES256_GCM,data:9bgt1ORrxxWUzk0=,iv:tndrORxlVP6HHgSthsithCXWCzOAsk1QnxvmZO8Ux3w=,tag:M+Xm5j59rgUQFEkyVJKSlw==,type:str]
type: ENC[AES256_GCM,data:IQNcTxJUhpmJAlkmzOrC6GSVRgMQZAtWfToNvDPc,iv:5fiKPH4OvavUhCBzNg684xeX3wVPHcrQmXSIATrEqjA=,tag:ZQ6qKutEB7/eXw2paRPwmg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:c/OiZfzwHkQUN1fveL12OU+GovGVoeRneTlbKGHRd8mydKsQYMz+/7Sa2DD1zzAg4Q31q3Ou/ofi/tUWXbGOgFR0/DEHsx7r/7wZFNnkB1YpGynBma5kUYs4IN+JzuMwY4UYqTuPbifPc/Np6ZqyzgklTGTSHAQNI++uxCNhyP4j1EqrmG0AMdCzGmiKR+4sULEKjkk1c04ESo1PnZrjIGkOFUw=,iv:q8UlB1MFK1mn60ruJvI3Y8KKn7WVfjlDCt7AzXmiIAk=,tag:rbkx+5SPhXT3fsKvlPD/Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWFpmOU5SYXVMMDNKRXBR
            ZzlYUXdDNDUxM0hhREhOL0M2SndSbXNQOXpzClVjTGdiVFhYeGltOThFeDZlRkpB
            cmZLYVJSU0RucjBwSnpmeFdYQVk5ZkkKLS0tIFBwVWFlTktDTUVKb3BSZXZ4UDhR
            VU9Oang5ZjFmR1cwcVhzaXVIM3I0MVkK6eZVfy+RTRe8gIbeCJKKcshckLDS82yE
            w0oQ+55oJIxedLldvJCp1SLlkhFdCWxaNm3VIxU/sKJNBZdNywvkww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T16:27:47Z"
    mac: ENC[AES256_GCM,data:qV+Cvy0EToDXNcDsJmZqstPSbnu6sl1Px8CqsGfgkVHzxYUITfX2BG3QQSv9XOdjSBfg+SkCfIYStf5pBu+rojmpYr0Yp9cc+g0dvMCe+++B07AVbxknLumX0CvZSzrJ9hI+yf3QP2BB7u3+4Q92uQtk3TgPPnWbIFjmMrGxmOY=,iv:WFrudCgnKF7+eR9gufywKf6ic5d6kLGf3JlsgezwE/M=,tag:75U7MIl2SKG7ngDTFxXZwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
